### ISSUE TITLE
Feasibility question

### ISSUE THREAD

**Issue by markrivasrobertson** [markrivasrobertson/project_2#2]
Hey, quick question about feasibility.  I want to add user authorized access.  In class we really only walked through a general single state behind a single authorization wall that any user who signed in could access.  I was wondering if you thought it was too much for me to try and have different levels of authorization.  For instance, if I look at my own facebook i can edit contents, but a friend looking at it can only add comments or likes.  I was thinking of my site having similar features, so my individual dashboard page on my app could be viewed by anyone logged in, but only when I view it while logged in as myself would certain edit buttons appear.  Should set this as part of MVP, or as a bonus, or is it a bridge too far for this whole project?

**Comment by ddruker** [comment]
Hey Mark,  I would say focus on getting basic auth setup and have that be a bonus.  You're then diving into the idea of permissions. It is an awesome topic but not a requirement for this project.
